before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: YSpnDltpDpkCInuE/VDxkMCcw31dSnpNG9g9r/94ZwFATG5ArjTD8NpbRKt1Y/so/rBeoayPflAhLTl4UAB1Gmpe7pSruHQl5NzruhJ/6SDccvUCzu+LN789/Q4k73G90Vk5lD+oDFncUx4CbzvXhVXfIePP1Y7Zlx15Y2Ofi4Bxnzh3j2Zs3CMYF+pjjE2FuEArRBVbFuOAKCCdKfgbQKy6QAE2ch5RLEDD5dZabJ4ZGK+V1IhjxIvLT0pglsc4rScXjtHAtZswviXRkWUpN2Ej++PlnkJvrqe4F/f/eDuIP8BCsKUVbEr1PLjnNruBk3QDViB19Dfe9cfCXPNWv6mkJZgl7j0EDJjCLkbva6PK/Y/dfw5ftCko4pjgnSUT+BNcLMBv1DV8mmrVLcGX9Y2eaU25cxh8U3g1KFNU8m9zwrHVDueWll4v8s4CRCQQ8z6MKLvL6VBr+WQec0qEqAzdbONRgNAS5cBQBpDZnsFZD4DctvqxcYd8tqEHka14HLcqllsL98AuD5Dy0ZuJnng1hDtEItyiMD7BzcZkvQWvlBLiPBlYNvrP0GqBycyaaDMHryF2W1mGhk3kArXMKMRt9iRW9xae4eNTmPQ0ESTy0TP6i0eQ4J5JAmdjAfoPyHK84P4JbZMH0ULJXNszhRNX8vED3d8hN/lMHdTmx0U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
